services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - ./..:/app

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./..:/app

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
  
  publisher:
    image: python:3.9-slim
    depends_on:
      - nats-server
    environment:
      - NATS_SERVER=nats-server:4222
    volumes:
      - ./publisher:/app
    working_dir: /app
    command: ["python", "publisher.py"]
  
  subscriber:
    image: python:3.9-slim
    depends_on:
      - nats-server
    environment:
      - NATS_SERVER=nats-server:4222
    volumes:
      - ./subscriber:/app
    working_dir: /app
    command: ["python", "subscriber.py"]